# Generated by Django 5.1.2 on 2024-11-04 17:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eucusers',
            name='abdomen',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='address',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='age',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='bp',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='date_of_exam',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='ears_vision_left',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='ears_vision_right',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='eyes_vision_left',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='eyes_vision_right',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='fathers_contact',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='fathers_name',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='fathers_occupation',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='height',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='lungs',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='medical_history',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='mothers_contact',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='mothers_name',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='mothers_occupation',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='mouth',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='nose',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='skin',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='status',
        ),
        migrations.RemoveField(
            model_name='eucusers',
            name='weight',
        ),
        migrations.CreateModel(
            name='EucHealthClinicInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment', models.CharField(blank=True, max_length=150, null=True)),
                ('medicine', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EucStudents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(blank=True, choices=[('default', 'Choose not to say'), ('male', 'Male'), ('female', 'Female')], max_length=20, null=True)),
                ('date_of_exam', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('contact_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=50, null=True)),
                ('fathers_contact', models.IntegerField(blank=True, null=True)),
                ('fathers_occupation', models.CharField(blank=True, max_length=150, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mothers_contact', models.IntegerField(blank=True, null=True)),
                ('mothers_occupation', models.CharField(blank=True, max_length=150, null=True)),
                ('medical_history', models.CharField(blank=True, max_length=255, null=True)),
                ('height', models.CharField(blank=True, max_length=30, null=True)),
                ('weight', models.CharField(blank=True, max_length=30, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('eyes_vision_right', models.CharField(blank=True, max_length=50, null=True)),
                ('eyes_vision_left', models.CharField(blank=True, max_length=50, null=True)),
                ('ears_vision_right', models.CharField(blank=True, max_length=50, null=True)),
                ('ears_vision_left', models.CharField(blank=True, max_length=50, null=True)),
                ('skin', models.CharField(blank=True, max_length=50, null=True)),
                ('mouth', models.CharField(blank=True, max_length=50, null=True)),
                ('nose', models.CharField(blank=True, max_length=50, null=True)),
                ('bp', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.CharField(blank=True, max_length=50, null=True)),
                ('lungs', models.CharField(blank=True, max_length=50, null=True)),
                ('abdomen', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.CharField(blank=True, max_length=150, null=True)),
                ('year_level', models.CharField(blank=True, max_length=30, null=True)),
                ('medicine_treatment', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.CharField(blank=True, max_length=150, null=True)),
                ('date_of_visit', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
