# Generated by Django 5.1.2 on 2024-11-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_eucusers_abdomen_remove_eucusers_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='euchealthclinicinventory',
            name='total_equipment',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='euchealthclinicinventory',
            name='total_medicine',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
